name: Plugin CI

on:
  push:
      branches:
        - release

jobs:
  super-lint:
    name: Code Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
